apiVersion: v1
kind: Service
metadata:
  name: vick-wso2sp-worker
  namespace: vick-system
spec:
  type: NodePort
  ports:
  - port: 9091
    name: http2
    protocol: TCP
  - port: 9092
    name: http
    protocol: TCP
  - port: 9411
    name: zipkin
    protocol: TCP
  - port: 9443
    name: https-mcgw-upload
    protocol: TCP
  - port: 9090
    name: http-mcgw-upload
    protocol: TCP
  - port: 7611
    name: tcp-thrift
    protocol: TCP
  - port: 7711
    name: tcp-ssl-thrift
    protocol: TCP
  - port: 9611
    name: tcp-binary
    protocol: TCP
  - port: 9711
    name: tcp-ssl-binary
    protocol: TCP
  - port: 7443
    name: http-global-gw
    protocol: TCP
  selector:
    app: vick-wso2sp-worker
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vick-wso2sp-worker
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vick-wso2sp-worker
    spec:
      containers:
      - name: vick-wso2sp-worker
        image: "vick-wso2sp-worker:4.3.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9091
        - containerPort: 9092
        - containerPort: 9411
        - containerPort: 9443
        - containerPort: 9090
        - containerPort: 7611
        - containerPort: 7711
        - containerPort: 9611
        - containerPort: 9711
        - containerPort: 7443
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myssqlervice; sleep 30; done;']
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: vick-wso2sp-dashboard-service
#  namespace: vick-system
#spec:
#  type: NodePort
#  ports:
#  - port: 9714
#    name: binary-ssl
#    protocol: TCP
#    targetPort: 9714
#  - port: 9643
#    name: portal
#    protocol: TCP
#    targetPort: 9643
#  - port: 9614
#    name: binary-tcp
#    protocol: TCP
#    targetPort: 9614
#  - port: 7713
#    name: thrift-ssl
#    protocol: TCP
#    targetPort: 7713
#  - port: 7613
#    name: thrift-tcp
#    protocol: TCP
#    targetPort: 7613
#  selector:
#    app: vick-wso2sp-dashoard
apiVersion: v1
kind: Service
metadata:
  name: vick-wso2sp-dashboard-service
  namespace: vick-system
spec:
  type: NodePort
  ports:
  - port: 9643
    name: http
    protocol: TCP
  selector:
    app: vick-wso2sp-dashoard
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vick-wso2sp-dashboard
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vick-wso2sp-dashboard
    spec:
      containers:
      - name: vick-wso2sp-dashboard
        image: "vick-wso2sp-dashboard:4.3.0"
        imagePullPolicy: IfNotPresent
        ports:
#        - containerPort: 9714
        - containerPort: 9643
#        - containerPort: 9614
#        - containerPort: 7713
#        - containerPort: 7613
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myssqlervice; sleep 30; done;']